# Generated by Django 4.2.2 on 2024-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='board_state',
            field=models.TextField(blank=True, default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', help_text='Almacena la posición de las piezas en formato FEN', null=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('FINISHED', 'finished')], default='PENDING', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='timeControl',
            field=models.CharField(blank=True, help_text='Control de tiempo para cada jugador', max_length=50, null=True, verbose_name='Time Control'),
        ),
    ]
