# Generated by Django 4.2.2 on 2024-05-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_chessgame_board_state_alter_chessgame_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('FINISHED', 'finished')], default='pending', max_length=64, null=True),
        ),
    ]
